nitrodb.dataDir=./data
nitrodb.memTableSizeBytes=67108864
nitrodb.blockCacheSizeBytes=268435456
nitrodb.blockSizeBytes=4096
nitrodb.maxLevels=7
nitrodb.levelSizeMultiplier=10
nitrodb.l1MaxBytes=268435456
nitrodb.bloomFalsePositiveRate=0.01
nitrodb.syncWrites=false
nitrodb.walSyncMode=ASYNC
nitrodb.compactionIntervalMs=1000
nitrodb.maxImmutableCount=4
nitrodb.targetSSTableSizeBytes=67108864
nitrodb.walSegmentSizeBytes=67108864
nitrodb.numCacheShards=16
nitrodb.checksumVerification=true
