nitrodb.dataDir=./data
nitrodb.memTableSizeBytes=1048576
nitrodb.blockCacheSizeBytes=16777216
nitrodb.blockSizeBytes=4096
nitrodb.maxLevels=4
nitrodb.levelSizeMultiplier=10
nitrodb.l1MaxBytes=16777216
nitrodb.bloomFalsePositiveRate=0.01
nitrodb.syncWrites=false
nitrodb.walSyncMode=ASYNC
nitrodb.compactionIntervalMs=250
nitrodb.maxImmutableCount=2
nitrodb.targetSSTableSizeBytes=1048576
nitrodb.walSegmentSizeBytes=1048576
nitrodb.numCacheShards=4
nitrodb.checksumVerification=true
