nitrodb.dataDir=./data
nitrodb.memTableSizeBytes=134217728
nitrodb.blockCacheSizeBytes=268435456
nitrodb.blockSizeBytes=4096
nitrodb.maxLevels=7
nitrodb.levelSizeMultiplier=10
nitrodb.l1MaxBytes=536870912
nitrodb.bloomFalsePositiveRate=0.02
nitrodb.syncWrites=false
nitrodb.walSyncMode=ASYNC
nitrodb.compactionIntervalMs=500
nitrodb.maxImmutableCount=8
nitrodb.targetSSTableSizeBytes=134217728
nitrodb.walSegmentSizeBytes=134217728
nitrodb.numCacheShards=32
nitrodb.checksumVerification=true
